### ISSUE TITLE
建议把原文件和转码后的分开来

### ISSUE THREAD

**Issue by bruceCzK** [xpipi001/ck2-2.81-localisation#2]
建议增加一个 release 文件夹，把转码后的文件放里面，另外也可以把英文的文件放一个文件夹，方便校对，翻译的人也不用自己转码

**Comment by xpipi001** [comment]
目前的文件都是未转码的，我另外弄一个转码的文件夹，到时候用于release。至于英文文本，稍后我上传一个，有需要的可以校对。最开始我传的是2.81合并2.63版本的，有中文的条目应该自动替换了。这几天的工作是在校对原来有翻译的文本在2.81里英文有变动的。全新增加的晚点再弄。

**Comment by bruceCzK** [comment]
感谢。另外我觉得可能要把 ck2SpeacialEscape 的实现写成一个脚本（Python?），这样发布的话直接在项目里跑一遍就行了，不太懂 C++，得研究一下
https://github.com/matanki-saito/CK2SpecialEscape/blob/master/ck2speacialescape/ck2speacialescape/ck2speacialescape.cpp

**Comment by xpipi001** [comment]
我不是程序员，不懂这个。本来的计划是文本翻译好了以后，我一并转了再上传。
